model: "rec"
recovery: "grad"
s: 0.1
f: 0.4
sim: 10
n: 100
resamp: 100
deme: 2025765288236
gen1: 40002
gen2: 40002
midchrom: 33759515
chrom: [21, 22]
OUTMAIN: "/home/lnd775/data/buffalo/simulations/reg_burn/KNP_tweek/results/"
dead: 40002
