model: "add"
recovery: "grad"
v: 1.0
f: 0.4
sim: 10
n: 500
resamp: 100
deme: 1
gen1: 58796
gen2: 58810
midchrom: 33759515
chrom: [21, 22]
OUTMAIN: "output"
ihs_best: "results/plots/40001_40017/rec_grad_s0.1_f0.3_sim_n100_ihsBest.txt"
dead:
